import { useState, useMemo } from 'react'

const QUESTIONS = [
  {
    topic: 'GREEN COVER',
    topicKey: 'green',
    question: 'What is the primary ecological benefit of a green roof in an urban setting?',
    options: [
      'Reduces stormwater runoff and the urban heat island effect',
      'Increases the structural load of the building',
      'Speeds up rainwater drainage to street level',
      'Reduces biodiversity by replacing natural habitat',
    ],
    correct: 0,
    explanation: 'Green roofs absorb rainwater and insulate buildings, reducing both stormwater runoff and surface temperatures — two of the biggest pressures on urban ecology.',
  },
  {
    topic: 'WATER CONSERVATION',
    topicKey: 'water',
    question: 'What does permeable paving allow that conventional asphalt does not?',
    options: [
      'Faster surface runoff after heavy rain',
      'Rainwater to infiltrate into the ground below',
      'Greater heat absorption from sunlight',
      'Reduced plant growth in surrounding areas',
    ],
    correct: 1,
    explanation: 'Permeable paving has gaps or porous material that lets rainwater pass through to soil and groundwater below, rather than rushing into drains.',
  },
  {
    topic: 'GREEN COVER',
    topicKey: 'green',
    question: 'Trees cool cities partly through transpiration. What is transpiration?',
    options: [
      'Reflection of sunlight from the surface of leaves',
      'Absorption of carbon dioxide during photosynthesis',
      'Release of water vapour through the pores of leaves',
      'Root absorption of pollutants from the soil',
    ],
    correct: 2,
    explanation: 'Transpiration is when plants release water vapour through tiny pores in their leaves. This evaporation process cools the surrounding air — the same principle as sweating.',
  },
  {
    topic: 'WATER CONSERVATION',
    topicKey: 'water',
    question: 'A rain garden is primarily designed to:',
    options: [
      'Collect and purify water for drinking',
      'Replace underground drainage pipe networks',
      'Slow, absorb and filter stormwater runoff',
      'Increase surface temperatures around buildings',
    ],
    correct: 2,
    explanation: 'Rain gardens are shallow planted depressions that capture stormwater, slow it down, and let it soak into the ground — reducing flooding and filtering out pollutants.',
  },
  {
    topic: 'WATER CONSERVATION',
    topicKey: 'water',
    question: 'Urban wetlands provide which key water management service?',
    options: [
      'They increase flood peaks in downstream rivers',
      'They filter pollutants and store excess floodwater',
      'They reduce local biodiversity over time',
      'They accelerate groundwater depletion',
    ],
    correct: 1,
    explanation: 'Wetlands act as natural sponges — absorbing floodwaters and filtering out pollutants before water flows into rivers and aquifers. Removing them increases flood risk significantly.',
  },
  {
    topic: 'URBAN HEAT',
    topicKey: 'heat',
    question: 'What is the urban heat island effect?',
    options: [
      'Cities receiving significantly more rainfall than rural areas',
      'Urban areas being measurably warmer than surrounding rural land',
      'Heat generated by underground infrastructure and pipes',
      'Temperature increases inside poorly insulated buildings',
    ],
    correct: 1,
    explanation: 'Hard surfaces like asphalt and concrete absorb and re-emit far more heat than vegetation. This makes cities several degrees warmer than nearby rural areas — especially at night.',
  },
  {
    topic: 'GREEN COVER',
    topicKey: 'green',
    question: 'Street trees reduce the urban heat island effect primarily by:',
    options: [
      'Acting as windbreaks along traffic corridors',
      'Absorbing vehicle exhaust and particulates',
      'Providing shade and releasing moisture through transpiration',
      'Reflecting excess heat back into the upper atmosphere',
    ],
    correct: 2,
    explanation: 'Street tree canopies shade pavements and buildings while their transpiration releases moisture — both of which significantly cool the surrounding microclimate.',
  },
  {
    topic: 'WATER CONSERVATION',
    topicKey: 'water',
    question: 'A rainwater harvesting system typically captures water for:',
    options: [
      'Direct drinking without any treatment',
      'Non-potable uses like irrigation and toilet flushing',
      'Heating buildings during winter months',
      'Generating electricity via micro-turbines',
    ],
    correct: 1,
    explanation: 'Harvested rainwater is used for non-potable purposes — watering gardens, flushing toilets, washing vehicles — reducing demand on treated drinking water supplies.',
  },
  {
    topic: 'GREEN COVER',
    topicKey: 'green',
    question: 'Many cities target 30% tree canopy cover. Why is 30% significant?',
    options: [
      'It maximises timber production within city limits',
      'It is the minimum required for photosynthesis to occur',
      'Evidence shows it delivers measurable cooling and stormwater benefits',
      'It is a requirement under international building codes',
    ],
    correct: 2,
    explanation: 'Research shows that 30% canopy cover is the threshold at which urban forests deliver significant ecological services: cooling, air quality improvement, and stormwater absorption.',
  },
  {
    topic: 'URBAN HEAT',
    topicKey: 'heat',
    question: 'Which surface reaches the highest temperature on a hot sunny day?',
    options: [
      'A grass lawn',
      'A green roof with sedum plants',
      'Dark asphalt pavement',
      'Gravel with stone mulch',
    ],
    correct: 2,
    explanation: 'Dark asphalt can reach surface temperatures of 60–70°C on a sunny day. Vegetated surfaces stay far cooler because plants use incoming solar energy for transpiration rather than heat storage.',
  },
]

const TOPIC_COLORS = {
  green: '#00ff88',
  water: '#00d4ff',
  heat:  '#ffaa00',
}

const ROUND_SIZE = 5

function shuffle(arr) {
  return [...arr].sort(() => Math.random() - 0.5).slice(0, ROUND_SIZE)
}

export default function Station3Environment({ onComplete, currentValue }) {
  const questions = useMemo(() => shuffle(QUESTIONS), [])
  const [index,    setIndex]    = useState(0)
  const [picked,   setPicked]   = useState(null)   // option index chosen
  const [score,    setScore]    = useState(0)
  const [done,     setDone]     = useState(false)

  const q = questions[index]
  const answered = picked !== null
  const isCorrect = picked === q?.correct

  const handlePick = (i) => {
    if (answered) return
    setPicked(i)
    if (i === q.correct) setScore(s => s + 1)
  }

  const handleNext = () => {
    if (index + 1 >= questions.length) {
      setDone(true)
    } else {
      setIndex(i => i + 1)
      setPicked(null)
    }
  }

  const handleRestart = () => {
    setIndex(0)
    setPicked(null)
    setScore(0)
    setDone(false)
  }

  /* ── RESULTS SCREEN ── */
  if (done) {
    const pct = Math.round((score / questions.length) * 100)
    const msg =
      pct === 100 ? 'PERFECT. You understand this city better than its planners.' :
      pct >= 80   ? 'STRONG — Ecological systems knowledge confirmed.' :
      pct >= 60   ? 'ADEQUATE — Gaps remain. The city is at risk.' :
      pct >= 40   ? 'WEAK — Critical knowledge missing. Urban systems under stress.' :
                    'CRITICAL — Ecological data insufficient. Intervention required.'

    return (
      <div className="station-environment">
        <div className="eco-done">
          <div className="eco-done-title">ANALYSIS COMPLETE</div>
          <div className="eco-results-score">
            <span className="eco-results-num">{score}</span>
            <span className="eco-results-denom">/ {questions.length}</span>
          </div>
          <div className="eco-done-bar">
            <div className="eco-done-fill" style={{ width: `${pct}%` }} />
          </div>
          <div className="eco-done-pct">{pct}%</div>
          <p className="eco-done-desc">{msg}</p>
          <div className="scramble-actions">
            <button className="confirm-btn" onClick={() => onComplete(pct)}>
              CONFIRM — {pct}%
            </button>
            <button className="skip-btn" onClick={handleRestart}>
              ↺ RESTART
            </button>
          </div>
        </div>
      </div>
    )
  }

  /* ── QUIZ SCREEN ── */
  const progress = ((index) / questions.length) * 100
  const topicColor = TOPIC_COLORS[q.topicKey]

  return (
    <div className="station-environment">

      {/* Header row: progress + score */}
      <div className="eco-quiz-header">
        <div className="eco-quiz-progress-wrap">
          <div className="eco-quiz-progress-bar">
            <div className="eco-quiz-progress-fill" style={{ width: `${progress}%` }} />
          </div>
          <span className="eco-quiz-count">{index + 1} / {questions.length}</span>
        </div>
        <div className="eco-quiz-score">SCORE <span>{score}</span></div>
      </div>

      {/* Topic badge */}
      <div className="eco-topic-badge" style={{ color: topicColor, borderColor: topicColor }}>
        {q.topic}
      </div>

      {/* Question */}
      <div className="eco-question">{q.question}</div>

      {/* Options */}
      <div className="eco-options-list">
        {q.options.map((opt, i) => {
          let cls = 'eco-quiz-option'
          if (answered) {
            if (i === q.correct)        cls += ' eco-opt-correct'
            else if (i === picked)      cls += ' eco-opt-wrong'
            else                        cls += ' eco-opt-disabled'
          }
          return (
            <button
              key={i}
              className={cls}
              onClick={() => handlePick(i)}
              disabled={answered}
            >
              <span className="eco-opt-letter">{String.fromCharCode(65 + i)}</span>
              <span className="eco-opt-text">{opt}</span>
              {answered && i === q.correct && <span className="eco-opt-tick">✓</span>}
              {answered && i === picked && i !== q.correct && <span className="eco-opt-cross">✗</span>}
            </button>
          )
        })}
      </div>

      {/* Feedback explanation */}
      {answered && (
        <div className={`eco-explanation ${isCorrect ? 'eco-expl-correct' : 'eco-expl-wrong'}`}>
          <span className="eco-expl-label">{isCorrect ? '✓ CORRECT' : '✗ INCORRECT'}</span>
          <span className="eco-expl-text">{q.explanation}</span>
        </div>
      )}

      {/* Next button */}
      {answered && (
        <button className="confirm-btn" onClick={handleNext}>
          {index + 1 >= questions.length ? 'VIEW RESULTS →' : 'NEXT QUESTION →'}
        </button>
      )}
    </div>
  )
}
